# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-15 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerie',
            name='image',
            field=models.ImageField(default='', upload_to='carousel_uploads', verbose_name='image'),
            preserve_default=False,
        ),
    ]
