# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-16 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gallerie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerie',
            name='image',
            field=models.ImageField(upload_to='gallerie_uploads', verbose_name='image'),
        ),
    ]
