# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-17 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180416_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerie',
            name='image',
            field=models.ImageField(upload_to='carousel_uploads', verbose_name='image'),
        ),
    ]
