# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-19 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180417_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Titre')),
                ('telephone', models.CharField(max_length=50, verbose_name='Telephone')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('date_arriver', models.CharField(max_length=50, verbose_name="Date d'arriver")),
                ('date_depart', models.CharField(max_length=50, verbose_name='Date de départ')),
                ('message', models.TextField(max_length=50, verbose_name='Message')),
                ('adultes', models.TextField(max_length=50, verbose_name='Adultes')),
                ('enfants', models.TextField(max_length=50, verbose_name='Enfants')),
            ],
        ),
    ]
