# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-19 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='adultes',
            field=models.CharField(max_length=50, verbose_name='Adultes'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='enfants',
            field=models.CharField(max_length=50, verbose_name='Enfants'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=300, verbose_name='Message'),
        ),
    ]
