# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-19 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180419_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='moyen',
            field=models.CharField(default='', max_length=50, verbose_name='moyen de contact preféré'),
            preserve_default=False,
        ),
    ]
